<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{8185e429-ba7a-41bc-99f3-636d37d5272b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_Sample();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>